env:
  browser: true
  es2021: true
  node: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
ignorePatterns: ["main.js"]
rules: 
  import/extensions: ["error", "ignorePackages", { "js": "always" }]
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  no-console: 0,
  no-unused-vars: 0,
  no-param-reassign: 0,
  indent: ["error", 2]
root: true
